### PR TITLE
fix circuit start issue

### LINKED ISSUE #15: Circuit start
Current implementation of [`circuit.firstProblem`](https://github.com/boolder-org/boolder-ios/blob/b418c9d55501a911de4b49b6b2a8b8d51ae2c403/Boolder/Models/Circuit.swift#L235) is not correct.

Sometimes there is a "start" problem before problem number one.
These problems are marked with `circuit_number=D`(D for "Départ")

### PR DESCRIPTION
**Pull request by one1color**
Fixes #15. As start, I have fixed issue of 15 (I saw some PR to this issue, but didn't seem active...)
Feel free to give me any feedback!

### CODE REVIEW

**Comment by nmondollot** [comment]
Thank you for your PR 🙏 

It works as intended 👍  but the code is a bit more complex than what I had in mind.
I think we can simplify it and make it easier to maintain in the future.

The 3 methods (`Circuit.firstProblem`, `Problem.next` and `Problem.previous`) could all rely on a method that understands the ordering of circuit numbers (like a sorted array or something using the Comparable protocol).

Other nitpicks:
- I'm not a fan of using `D` as a string in several places (it's not DRY), I think would be more robust to make it a constant (or  make the code more centralized)
- I wrote `self.circuitNumberComparableValue()` a long time ago, not sure it's a good thing to use it in this context (or we could clean it, and at least make it a property instead of a function)

**Comment by nmondollot** [comment]
PS: it may be easier to implement this in swift instead of SQL

**Comment by one1color** [comment]
@nmondollot Thanks for your feedback, I have set the "D" as defaultCircuitNumber constant value within Problem property, and not using the `self.circuitNumberComparableValue()` for now. I guess it is okay to fix the issue for now. We can talk about how to or where we will refactor next!

**Comment by nmondollot** [comment]
Ok!
Let's continue the discussion [here](https://github.com/boolder-org/boolder-ios/issues/45)

**Pull request merged**
